### ISSUE TITLE
Can't send JSON objects.

### ISSUE THREAD

**Issue by slorenzo** [GraphQLCollege/graphql-postgres-subscriptions#4]
Hi @JulianMayorga.
I was doing some tests over GraphQL subscriptions.
I'm having some troubles sending objects. I have dived deep into the libraries that you are using to make that and I found that each object becomes a string.

Look at this: [https://github.com/emilbayes/pg-ipc/blob/master/index.js#L34](https://github.com/emilbayes/pg-ipc/blob/master/index.js#L34)

I'm using Sequelize as a ORM, so when the instance went over this line, it drops a lot of properties.

Any suggest to avoid this?
Thanks in advance and great work with this library.

**Comment by JulianMayorga** [comment]
Hi @slorenzo,

Thanks so much for clearly explaining your issue.

As you noticed, all objects are serialized using `JSON.stringify`. I have not used Sequelized in a while. Have you tried calling [`toJSON`](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-toJSON) on your models? I assume that doing this won't result in lost properties.

Let me know what you think, I would be happy to help you with this issue.

Cheers!
Julian.

**Comment by slorenzo** [comment]
Yes, I have used `toJSON()`. When `toJSON()` or `JSON.stringify`  is called, it returns the fields from `dataValues`, but the instance has many field more.

Look at an example instance object:

```
Example {
  dataValues:
   { id: 8,
     name: '16e0a598-b4b3-41db-8e49-7c1543fee797',
     no_name_id: 3,
     updated_at: 2018-06-13T19:46:41.131Z,
     created_at: 2018-06-13T19:46:41.131Z,
     createdAt: 2018-06-13T19:46:41.131Z,
     updatedAt: 2018-06-13T19:46:41.131Z },
  _previousDataValues:
   { name: '16e0a598-b4b3-41db-8e49-7c1543fee797',
     no_name_id: 3,
     id: 8,
     createdAt: 2018-06-13T19:46:41.131Z,
     updatedAt: 2018-06-13T19:46:41.131Z,
     created_at: 2018-06-13T19:46:41.131Z,
     updated_at: 2018-06-13T19:46:41.131Z },
  _changed:
   { name: false,
     no_name_id: false,
     id: false,
     createdAt: false,
     updatedAt: false,
     created_at: false,
     updated_at: false },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: true,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [ [Object] ],
     name: { plural: 'Chats', singular: 'Chat' },
     omitNull: false,
     tableName: 'chats',
     associations: true,
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [PostgresDialect],
        queryInterface: [QueryInterface],
        models: [Object],
        modelManager: [ModelManager],
        connectionManager: [ConnectionManager],
        importCache: [Object],
        test: [Object] },
     hooks: {},
     uniqueKeys: {} },
  _options:
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
```
Sequelize gives me some features inside of the instances that I need to use it on resolvers. But, I can't because I just have the following object:

```
{ 
     id: 8,
     name: '16e0a598-b4b3-41db-8e49-7c1543fee797',
     no_name_id: 3,
     updated_at: 2018-06-13T19:46:41.131Z,
     created_at: 2018-06-13T19:46:41.131Z,
     createdAt: 2018-06-13T19:46:41.131Z,
     updatedAt: 2018-06-13T19:46:41.131Z 
}
```

Thanks for your quickly response!

**Comment by JulianMayorga** [comment]
Hmmm I understand.

A solution off the top of my head would be using `JSON.stringify` to serialize the fields you need. Something like `JSON.stringify({ ...obj.dataValues, ...obj._options })`, which would serialize the following string:

```json
{
  "id":8,
  "name":"16e0a598-b4b3-41db-8e49-7c1543fee797",
  "no_name_id":3,
  "updated_at":"2018-06-13T19:46:41.131Z",
  "created_at":"2018-06-13T19:46:41.131Z",
  "createdAt":"2018-06-13T19:46:41.131Z",
  "updatedAt":"2018-06-13T19:46:41.131Z",
  "isNewRecord":true,
  "_schema":null,
  "_schemaDelimiter":""
}
```

Do you think this makes sense? Let me know if I misunderstood the problem :D

**Comment by slorenzo** [comment]
I have tried different things but I couldn't solve my issue. I tried with [other package](https://github.com/davidyaha/graphql-redis-subscriptions) rather than your package and I realized that the problem is my architecture and the libraries I used.
I will upgrade my SQL layer to Prisma and leave Sequelize behind.

However, thanks for your help.

**Comment by JulianMayorga** [comment]
I understand, well, Prisma is a great choice for your database layer! If you have further questions in the future, I'm always happy to help.

¡Éxitos Sebastián!
