### ISSUE TITLE
Can't get a payload from pg_notify

### ISSUE THREAD

**Issue by timneedham** [GraphQLCollege/graphql-postgres-subscriptions#6]
Hi,

__First of all, thank you for writing this package, it's exactly what I need... I think! 😉__

* I'm really new to Apollo and GraphQL, `pubsub.asyncIterator` etc.
* Apologies if I'm being slow...

I would really appreciate some help with using/understanding `graphql-postgres-subscriptions`... especially in this scenario:

## Postgres

__Given a simple PostgreSQL table:__

``` sql
CREATE TABLE cards
(
  id uuid NOT NULL DEFAULT uuid_generate_v1(),
  title text NOT NULL
  CONSTRAINT cards_pkey PRIMARY KEY (id)
);
```

I've added a simple trigger:

``` sql

CREATE OR REPLACE FUNCTION f_card_changed() RETURNS trigger AS
$BODY$
DECLARE 
BEGIN
  PERFORM pg_notify('BOOM', '{"someKey": "How do I get this?"}');
  RETURN new;
END;
$BODY$
LANGUAGE plpgsql VOLATILE
COST 100;

CREATE TRIGGER card_changed_trg
  AFTER INSERT OR UPDATE
  ON cards
  FOR EACH ROW
  EXECUTE PROCEDURE f_card_changed();
```

So this fires on every insert/update of the `cards` table and fires a `NOTIFY` via:

`PERFORM pg_notify('BOOM', '{"someKey": "How do I get this?"}');`

__The good news...__ this does trigger an event, and the event appears in the GraphQL Playground! 😄 

However... I'm really struggling getting access to the __payload__ that the `NOTIFY` generated?

## Apollo

So on the Node server (Apollo) side, I'm:

__Schema__

```
type Subscription {
  cardChanges(cardId: String): String
}
```

__`graphql-postgres-subscriptions` setup__

``` javascript

// Setup
import { PostgresPubSub } from 'graphql-postgres-subscriptions'
const { Client } = require('pg')

// Need to pass-in a shared connection
const dbClient = new Client(
  {
    connectionString: 'XXXXX'
  }
)
dbClient.connect()

const pubsub = new PostgresPubSub(
  {
    client: dbClient
  }
)
```
__Resolver__
```
Subscription: {
  cardChanges: {
    subscribe: (parent, args, context) => {
      console.log('ARGS!', args)
      return pubsub.asyncIterator(['BOOM'])
    }
  }
}
```

So I get the event on every row-change... but I can't find a way of accessing the payload that's bundled in the `NOTIFY` message?

* Ideally I'd want to be passing some JSON object in the payload delivered from the database-trigger and having that end-up on the GraphQL client.
 
__Any help understanding what I'm doing wrong would be really appreciated.__

Kind regards

Tim

**Comment by timneedham** [comment]
DOH!

It's this, isn't it?

https://github.com/apollographql/graphql-subscriptions#payload-manipulation

**Comment by JulianMayorga** [comment]
I'm happy it's useful to you :D. Thanks for contributing!
