### ISSUE TITLE
Crash when sending long messages

### ISSUE THREAD

**Issue by derekpitt** [GraphQLCollege/graphql-postgres-subscriptions#7]
Hey there!

Thank you for this lib!!

I ran into an issue where my express web app crashed because I accidentally sent a message longer than 8000 characters. I have since changed that message to use an ID instead, but it is worth handling gracefully and documenting.

Here are some docs where it has the 8000 character limit.
https://www.postgresql.org/docs/9.0/static/sql-notify.html

Would you like for me to start a PR? I'd love to give back!

**Comment by JulianMayorga** [comment]
Fixed this in version 1.0.3, introduced by this PR https://github.com/GraphQLCollege/graphql-postgres-subscriptions/pull/9.

Subscribing to the `error` message should prevent the server from crashing when a postgres error happens. Adding something like `ps.subscribe("error", console.error);` should be enough.

Thanks for all the help @derekpitt
